name: Pull from Azure DevOps and Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Clone Azure DevOps repo
        run: |
          git clone https://$AZURE_PAT@dev.azure.com/your-org/your-project/_git/your-repo azure-repo
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}

      - name: List files from Azure repo
        run: ls -la azure-repo


